export const products = [
  {
    id: 1,
    store_id: 2,
    name: "prod 1 store 2",
    desc: "dkaslndas kldskaldnas kldnsmkaldn asl dsankdlsad asdas das d asd as d as das d as d",
    price: 15,
    img: "https://mui.com/static/images/cards/contemplative-reptile.jpg",
    quantity: 17,
  },
  {
    id: 2,
    store_id: 2,
    name: "prod 2 store 2",
    desc: "dkaslndas das d asd as d as das d as d",
    price: 15,
    img: "https://mui.com/static/images/cards/contemplative-reptile.jpg",
    quantity: 17,
  },
  {
    id: 3,
    store_id: 2,
    name: "prod 3 store 2",
    desc: "dkaslndas kldskaldnas kldn asl dsankdlsad asdas das d asd as d as das d as d",
    price: 15,
    img: "https://mui.com/static/images/cards/contemplative-reptile.jpg",
    quantity: 17,
  },
  {
    id: 4,
    store_id: 1,
    name: "prod 3 store 1",
    desc: "dkaslndas kldskaldnas kldn asl dsankdlsad asdas das d asd as d as das d as d",
    price: 15,
    img: "https://mui.com/static/images/cards/contemplative-reptile.jpg",
    quantity: 17,
  },
  {
    id: 5,
    store_id: 3,
    name: "prod 3 store 3",
    desc: "dkaslndas kldskaldnas kldn asl dsankdlsad asdas das d asd as d as das d as d",
    price: 15,
    img: "https://mui.com/static/images/cards/contemplative-reptile.jpg",
    quantity: 17,
  },
];
